### ISSUE TITLE
use ST for effects

### ISSUE THREAD

**Issue by matthewleon** [purescript-node/purescript-node-buffer#24]
Following `Data.Array.ST`'s example, mutations could live in the ST monad. Then creation and reading would not require `Eff`. This would be a very big change to the library's philosophy.

Thoughts?

**Comment by hdgarrood** [comment]
I think this is a good idea, definitely worth exploring. I think it might make sense to provide a new API inside this library, perhaps under the `Node.Buffer.ST` namespace, alongside the current API (hopefully we could do this in a non-breaking way). I think both approaches are useful in different scenarios, so I don't wouldn't want to replace the current API.

**Comment by hdgarrood** [comment]
Fixed by #33.
