### ISSUE TITLE
buffer construction uses deprecated methods

### ISSUE THREAD

**Issue by matthewleon** [purescript-node/purescript-node-buffer#26]
quoting https://nodejs.org/api/buffer.html#buffer_buffer

> To make the creation of Buffer instances more reliable and less error prone, the various forms of the new Buffer() constructor have been deprecated and replaced by separate Buffer.from(), Buffer.alloc(), and Buffer.allocUnsafe() methods.
>
> Developers should migrate all existing uses of the new Buffer() constructors to one of these new APIs.

**Comment by hdgarrood** [comment]
Thanks for the report! This was fixed by #31.
